name: "coverage"
on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npx jest --coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          threshold: 10
