# This workflow will run tests for PRs before allowing merge

name: Merge checks

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [16, 18]
        include:
          - os: ubuntu-latest
            npm_path: /home/runner/.npm/_logs/
          - os: macos-latest
            npm_path: /Users/runner/.npm/_logs/
          - os: windows-latest
            npm_path: C:\npm\cache\_logs
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: npm cit
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ matrix.npm_path }}
  coverage-report:
    uses: ./.github/workflows/jest_coverage_report.yml
    needs: run-tests
    permissions:
      checks: write
      pull-requests: write
      contents: write
